### ISSUE TITLE
Webpack describe

### ISSUE THREAD

**Issue by lyquocphong** [kulmann/moodle-mod_philosophers#22]
Hi !

I am interested in this project and would like to implement another simpler vue application than your. Can I ask that this project is mainly develop the vue app in vue folder and use webpack to build to lazy javascript file so moodle can use it. I would like to ask for the webpack describe because I am not export in that. How you communicate with moodle from your VUE application ?

**Comment by kulmann** [comment]
## for your vue app
There is a webpack config in the `vue` folder that is just taking care of building an `amd` from the vue application and putting it into the `amd` folder at the root level of the folder structure.

The communication of the vue app with moodle is solved through ajax calls, which are mostly placed in the vuex store of this application (file `vue/store.js`). There is an `ajax` helper at the bottom of the file, which is used throughout the store file: https://github.com/kulmann/moodle-mod_philosophers/blob/b3c8ad1ffad8624a0de082df8ba17abb7dca444f/vue/store.js#L439 

You can import other moodle amds in your code, see e.g. here: https://github.com/kulmann/moodle-mod_philosophers/blob/b3c8ad1ffad8624a0de082df8ba17abb7dca444f/vue/store.js#L3

## for your php code
Moodle plugins are written in PHP. I embedded my vue application in the `view.php` file by doing this amd require call: https://github.com/kulmann/moodle-mod_philosophers/blob/b3c8ad1ffad8624a0de082df8ba17abb7dca444f/view.php#L54
and by having this div: https://github.com/kulmann/moodle-mod_philosophers/blob/b3c8ad1ffad8624a0de082df8ba17abb7dca444f/view.php#L61
The vue app will mount itself into that div.

Unfortunately it gets more complicated for the communication part. For my application there is quite some php code for the data model on the server side and for registering ajax handlers within moodle. Have a look here: https://github.com/kulmann/moodle-mod_philosophers/tree/master/classes
The classes within the `external` dir are the ajax handlers - each ajax function you want to provide needs three different php functions. For a simple example with only one ajax function have a look here: https://github.com/kulmann/moodle-mod_philosophers/blob/master/classes/external/game.php 
As a last step you need an entry in your `db/services.php` file to register the ajax handler with a name that can be called from outside: https://github.com/kulmann/moodle-mod_philosophers/blob/b3c8ad1ffad8624a0de082df8ba17abb7dca444f/db/services.php#L61
The new ajax handlers will only be picked up by moodle if you increase the version number of your moodle plugin and run a migration (e.g. by visiting the website administration start page).

Hope this gives you a rough overview of the necessary steps. It is quite a lot to digest and figure out.
