### ISSUE TITLE
Server side rendering possible ?

### ISSUE THREAD

**Issue by lyquocphong** [kulmann/moodle-mod_philosophers#24]
Is it possible to apply server side rendering ? What is the best practice if my block has many view and each view will act different so I should render different entry point or use the same entry point and let vue-router do the thing ?

**Comment by kulmann** [comment]
Hey, I'd appreciate to answer questions about your application in your repository. ;-) Give me a link and I'll happily take a look at your code base. Without context it's hard to help out anyway.
